### ISSUE TITLE
inpainting is missing prompt

### ISSUE THREAD

**Issue by 1blackbar** [shinomakoi/sd-dreamer#1]
Results are weird without any prompt, it doesnt know what to do with inpanted area, i tried to remove eyes on a head, it cant do it

**Comment by shinomakoi** [comment]
There doesn't seem to be a way to give a prompt to stable diffusion's inpainting model. I don't know if it's possible, but am looking into ways to improve the inpainting

**Comment by 1blackbar** [comment]
So how its supposed to work then? Do you actually managed to make it work and remove a window on a house for example ? There is inpainting called LAMA that i use and it does not need prompting but with SD i think you need to prompt when inpainting
Heres demo for lama which does a great job without any prompting but it removes stuff mostly and fills in
https://cleanup.pictures/

Also there are several webuis that have inpainting using img2img but they dont use actual model that you do, maybe there is certain wayt you have to use the model you have for inpainting.
https://github.com/hlky/stable-diffusion-webui
https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by shinomakoi** [comment]
Yea the webui is using masking (like photoshop), blending parts of 2 images together while this is a dedicated inpainting model  with no option for a prompt that I can see (like lama). I heard they are bringing out a proper inpainting model soon. Until then I could try add masking like with WebUI and/or integrate something like lama.

**Comment by 1blackbar** [comment]
Yes but lama removes my eyes and stuff from background without issues and this model doesnt so  maybe it needs moar code to be released by stability to really make it work

**Comment by shinomakoi** [comment]
Has better inpainting now that uses prompts.
