### ISSUE TITLE
Multiple issues with latest commit

### ISSUE THREAD

**Issue by slack-t** [shinomakoi/sd-dreamer#2]
Hi,

First of all thank you for all the work and building this great Qt UI for SD!

I pulled the latest today but unfortunately found multiple issues...

- Missing "Optimized mode"
-- I have to use the basujindal fork's Optimized mode to be able to run SD on my crappy 3GB 1060, the current commit removed the Optimized checkbox and also the scripts I guess. Tried to replace the modules from the extras directory but no luck... This effectively breaks using this UI for me. People with proper video cards (more VRAM) probably won't bother...

- wrong path to settings.ini in txt2img_k_sdd_batch.py
-- paths in line 201 and 202 should be 'sd-dreamer/settings.ini' instead of 'sd_dreamer/settings.ini'

- Probably an issue with regional settings (on Windows) with float values
```
ValueError: could not convert string to float: '0,75'
Traceback (most recent call last):
  File "sd-dreamer\main.py", line 626, in dreamer_new
    strength = float(self.img2imgStrength.text())
ValueError: could not convert string to float: '0,75'
```
I changed line 626 in main.py to strength = float(self.img2imgStrength.text().replace(",",".")) to make it work for me. Don't think that's a great solution tho ;-)

Thanks,
Slack

**Comment by shinomakoi** [comment]
Thanks for feedback. I'll look into the bugs. Redid a lot of stuff in the last update so things are bit rough for now. I plan to add back in the optimised scripts soon. Bugs 2 and 3 fixed hopefully. BTW you can get the old version here: https://github.com/shinomakoi/sd-dreamer/tree/852ea7c6c4f971918727035146e93b3286d9612a

**Comment by slack-t** [comment]
Thank you @shinomakoi ! Yeah I figured, I liked the changes on the UI, so keep it up! 👍 
Yeah, I reset back to the commit that was working for me already.
Will close this for now.

**Comment by shinomakoi** [comment]
Optimized scripts are back! And better hopefully
