### ISSUE TITLE
Error while trying to run a prompt

### ISSUE THREAD

**Issue by rfariavitor** [shinomakoi/sd-dreamer#4]
Greetings.
I followed the Easy peasy Windows install guide on InvokeAI without problems, but when I try to run the main.py in the sd-dreamer it gives me the following output:

Traceback (most recent call last):
  File "G:\stable-diffusion\sd-dreamer\main.py", line 793, in dreamer_new
    batch = int(self.batchVal.value())
AttributeError: 'sd_dreamer_main' object has no attribute 'batchVal'

Since I saw no reference of batches in the UI, I removed that line 793 from main.py and now it's running.

**Comment by shinomakoi** [comment]
Oops, thought I pushed the fix for that. Thanks for letting me know

**Comment by shinomakoi** [comment]
Should be fixed now
